update

diff --git a/.github/workflows/ci-backend-build.yaml b/.github/workflows/ci-backend-build.yaml
--- a/.github/workflows/ci-backend-build.yaml
+++ b/.github/workflows/ci-backend-build.yaml
@@ -82,20 +82,20 @@ jobs:
           fi
           ###### Handle Pull & Push Retry ######
           retry=0
-          while [ "$retry" -lt 3 ]
+          while [ "${retry}" -lt 3 ]
           do
-            git pull https://${{ secrets.CRC_GIT_USER }}:${{ secrets.CRC_GIT_TOKEN }}@github.com/digital-ventures/crc-app-deployment.git && git push https://${{ secrets.CRC_GIT_USER }}:${{ secrets.CRC_GIT_TOKEN }}@github.com/digital-ventures/crc-app-deployment.git || ppResult=$?;
-            echo -e "\e[31m P&P Result \e[0m : \e[96m $ppResult";
-            if [[ $ppResult == "" || $ppResult -eq 0 ]]; then
+            git pull https://${{ secrets.CRC_GIT_USER }}:${{ secrets.CRC_GIT_TOKEN }}@github.com/digital-ventures/crc-app-deployment.git && git push https://${{ secrets.CRC_GIT_USER }}:${{ secrets.CRC_GIT_TOKEN }}@github.com/digital-ventures/crc-app-deployment.git || ppResult=$?
+            echo -e "\e[31m P&P Result \e[0m : \e[96m ${ppResult}"
+            if [[ ${ppResult} == "" || ${ppResult} -eq 0 ]]; then
               echo -e "\e[92m Update Deployment success \e[0m"
               break
             else
               retry=$((retry+1))
-              if [ "$retry" -eq 3 ]; then
-                echo -e "\e[31m Update Deployment failed, limit exceeded, MANUAL RETRY NEEDED \e[0m";
+              if [ "${retry}" -eq 3 ]; then
+                echo -e "\e[31m Update Deployment failed, limit exceeded, MANUAL RETRY NEEDED \e[0m"
                 exit 1
               else
-                echo -e "\e[93m Update Deployment failed, retrying : \e[96m $retry \e[0m";
+                echo -e "\e[93m Update Deployment failed, retrying : \e[96m ${retry} \e[0m"
               fi
             fi
           done
